In [4]:
import unittest
import PackitArena as Arena
from PackitMCTS import MCTS
import numpy as np
from utils import * 
from TriangleGame.TriangleGame import TriangleGame
from TriangleGame.TrianglePlayers import RandomPlayer
from TriangleGame.keras.NNet import NNetWrapper as TriangleNNet
from TriangleGame.keras.NNetSmall import NNetWrapper as TriangleNNetSmall

In [3]:
def execute_game_test(game, neural_net):
    rp = RandomPlayer(game).play


    args = dotdict({'numMCTSSims': 25, 'cpuct': 1.0})
    mcts = MCTS(game, neural_net(game), args)
    n1p = lambda x, t: np.argmax(mcts.getActionProb(x, t, temp=0))
    arena = Arena.Arena(n1p, rp, game)
    print(arena.playGames(2, verbose=True))

In [7]:
execute_game_test(TriangleGame(7), TriangleKerasNNet)
#final representation of game is wrong for triangles because unavailable fields are 0 not 1 as in hex

Arena.playGames (1):   0%|                                                                       | 0/1 [00:00<?, ?it/s]

Turn  1 Player  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
Turn  2 Player  -1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]]
Turn  3 Player  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]]
Turn  4 Player  -1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0]]
Turn  5 Player  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0

Arena.playGames (1): 100%|███████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.56s/it]


Turn  8 Player  -1
[[1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 1 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 0 0 0 0 0]]
Game over: Turn  8 Result: Player  -1  wins!
[[ 5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  5  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  5  0  3  3  0  0  0  0  0  0  0  0]
 [ 5  5  0  0  0  3  3  0  0  0  0  0  0]
 [ 1  6  6  6  6  6  2  0  7  0  0  0  0]
 [ 1  1  0  6  6  6  2  2  7  7  7  0  0]
 [ 0  4  4  4  4  4 -1  2  0  7  7  7  7]]


Arena.playGames (2):   0%|                                                                       | 0/1 [00:00<?, ?it/s]

Turn  1 Player  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
Turn  2 Player  -1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
Turn  3 Player  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
Turn  4 Player  -1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 0]]
Turn  5 Player  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 1

Arena.playGames (2): 100%|███████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.41s/it]

Turn  7 Player  1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 1 1 1 1 0 1 0 0 0]]
Turn  8 Player  -1
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 0 1 1 0 0 0 0]
 [0 1 0 0 1 1 1 1 0 1 0 0 0]]
Game over: Turn  8 Result: Player  -1  wins!
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  3  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  3 -1  1  1  0  0  0  0  0  0  0  0]
 [ 0  3  0 -1  5  7  7  0  0  0  0  0  0]
 [ 4  4  6  6  6  5  5  7  7  0  0  0  0]
 [ 4  4  6  6  6  6  0  5  5  7  7  0  0]
 [ 0  4  0  0  2  2  2  2  0  5  0  7  7]]
Player      Going First       Going Second   
---------------------------------------------
Player 1    0                 1              
Player 2    0                 1              
(1, 1, 0)


In [32]:
def test_against_random(game, nnet, args, num_games):

    mcts = mcts = MCTS(game, nnet, args)
    rp = RandomPlayer(game).play
    n1p = lambda x, t: np.argmax(mcts.getActionProb(x, t, temp=0))
    arena = Arena.Arena(n1p, rp, game)
    print(arena.playGames(num_games, verbose=False))

In [33]:
game = TriangleGame(5)
nnet = TriangleKerasNNet(game)
nnet.load_checkpoint(folder = "tri_temp", filename = "temp")
args = dotdict({'numMCTSSims': 25, 'cpuct': 1.0})

test_against_random(game, nnet, args, 20)

Arena.playGames (2): 100%|█████████████████████████████████████████████████████████████| 10/10 [00:20<00:00,  2.02s/it]

Player      Going First       Going Second   
---------------------------------------------
Player 1    9                 7              
Player 2    1                 3              
(16, 4, 0)


In [2]:
from PackitAIPlayer import AIPlayer

aip = AIPlayer(3)

Local weights file not found
Accessing  https://huggingface.co/lgfn/packit-polygons-models/resolve/main/triangle_models/size_3/best.weights.h5
Checkpoint Directory does not exist! Making directory ./packit-polygons-models/triangle_models/size_3/


In [5]:
def execute_game_test_aip(aip):
    rp = RandomPlayer(aip.game).play
    aip_play = aip.nnet_get_action
    arena = Arena.Arena(aip_play, rp, aip.game)
    print(arena.playGames(2, verbose=False))

In [6]:
execute_game_test_aip(aip)

Arena.playGames (1):   0%|                                                                              | 0/1 [00:00<?, ?it/s]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
aip.nnet_get_action(aip.game.getInitBoard(), 1)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
RandomPlayer(aip.game).play(aip.game.getInitBoard(), 1)

np.int64(17)

In [30]:
a= 'dfijvbbndf'
b = 'fjsnvijn'
c=a+b
c

'dfijvbbndffjsnvijn'

In [31]:
a+=b
a

'dfijvbbndffjsnvijn'

In [ ]:
aip(

In [12]:
import tensorflow as tf
g = TriangleGame(3)
nnet = TriangleNNetSmall(g)
nnet.nnet.model.load_weights(tf.keras.utils.get_file('best.weights.h5', 'https://huggingface.co/lgfn/packit-polygons-models/resolve/main/triangle_models/size_3/best.weights.h5'))

C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 46 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))
