In [31]:
import unittest
import PackitArena as Arena
from PackitMCTS import MCTS
import numpy as np
from utils import * 
from TriangleGame.TriangleGame import TriangleGame
from TriangleGame.TrianglePlayers import RandomPlayer
from TriangleGame.keras.NNet import NNetWrapper as TriangleKerasNNet

In [25]:
def execute_game_test(game, neural_net):
    rp = RandomPlayer(game).play


    args = dotdict({'numMCTSSims': 25, 'cpuct': 1.0})
    mcts = MCTS(game, neural_net(game), args)
    n1p = lambda x, t: np.argmax(mcts.getActionProb(x, t, temp=0))
    arena = Arena.Arena(n1p, rp, game)
    print(arena.playGames(2, verbose=True))

In [26]:
execute_game_test(TriangleGame(5), TriangleKerasNNet)
#final representation of game is wrong for triangles because unavailable fields are 0 not 1 as in hex

Arena.playGames (1):   0%|                                                                       | 0/1 [00:00<?, ?it/s]

Turn  1 Player  1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
Turn  2 Player  -1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
Turn  3 Player  1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


Arena.playGames (1): 100%|███████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.29s/it]


Turn  4 Player  -1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0]]
Turn  5 Player  1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0]
 [1 1 1 0 0 1 1 0 0]
 [0 0 0 0 1 1 1 0 0]]
Game over: Turn  5 Result: Player  1  wins!
[[ 4  0  0  0  0  0  0  0  0]
 [ 4  4  0  0  0  0  0  0  0]
 [ 4  4  0  3  3  0  0  0  0]
 [-1  1  1  0  0  3  3  0  0]
 [ 0  0  0  0  2  2  2  0  0]]


Arena.playGames (2):   0%|                                                                       | 0/1 [00:00<?, ?it/s]

Turn  1 Player  1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
Turn  2 Player  -1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
Turn  3 Player  1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0]]
Turn  4 Player  -1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0]
 [1 1 1 0 0 0 0 0 0]]


Arena.playGames (2): 100%|███████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.16s/it]

Turn  5 Player  1
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 0 0]]
Game over: Turn  5 Result: Player  1  wins!
[[ 0  0  0  0  0  0  0  0  0]
 [ 4  4  4  0  0  0  0  0  0]
 [ 0  4  4  4  0  0  0  0  0]
 [ 0  0  0 -1 -1  1  1  0  0]
 [ 2  2  2  3  3  3  3  0  0]]
Player      Going First       Going Second   
---------------------------------------------
Player 1    1                 0              
Player 2    0                 1              
(1, 1, 0)


In [32]:
def test_against_random(game, nnet, args, num_games):

    mcts = mcts = MCTS(game, nnet, args)
    rp = RandomPlayer(game).play
    n1p = lambda x, t: np.argmax(mcts.getActionProb(x, t, temp=0))
    arena = Arena.Arena(n1p, rp, game)
    print(arena.playGames(num_games, verbose=False))

In [33]:
game = TriangleGame(5)
nnet = TriangleKerasNNet(game)
nnet.load_checkpoint(folder = "tri_temp", filename = "temp")
args = dotdict({'numMCTSSims': 25, 'cpuct': 1.0})

test_against_random(game, nnet, args, 20)

Arena.playGames (2): 100%|█████████████████████████████████████████████████████████████| 10/10 [00:20<00:00,  2.02s/it]

Player      Going First       Going Second   
---------------------------------------------
Player 1    9                 7              
Player 2    1                 3              
(16, 4, 0)
